model_name: xgboost_20250904_212754
Type: XGBoostClassifier
artifact_paths:
  scaler: xgboost_20250904_212754_scaler.pkl
  model: xgboost_20250904_212754_model.json
Config:
  model_params:
    objective: multi:softmax
    eval_metric: mlogloss
    n_estimators: 150
    learning_rate: 0.1
    max_depth: 4
    use_label_encoder: false
    num_class: 5
  features:
  - open
  - high
  - low
  - close
  - volume
  - supertrendcciv2_9_9_9_exponential_true_standard_10_2.618_14_atr_100_-100_#ff32cd32_#ffff0000_#ff808080_cci
  - supertrendcciv2_9_9_9_exponential_true_standard_10_2.618_14_atr_100_-100_#ff32cd32_#ffff0000_#ff808080_ccima
  - supertrendcciv2_9_9_9_exponential_true_standard_10_2.618_14_atr_100_-100_#ff32cd32_#ffff0000_#ff808080_supertrend
  - supertrendcciv2_9_9_9_exponential_true_standard_10_2.618_14_atr_100_-100_#ff32cd32_#ffff0000_#ff808080_trenddirection
  - pricedistances__dist_ema_9
  - pricedistances__dist_ema_21
  - pricedistances__dist_t3_48
  - pricedistances__dist_copen
  - pricedistances__dist_chigh
  - pricedistances__dist_clow
  - pricedistances__dist_popen
  - pricedistances__dist_phigh
  - pricedistances__dist_plow
  - pricedistances__dist_pclose
  - pricedistances__dist_vwap
  - waddahattarexplosion deadzone_150_10_true_9_30_true_9_30_2_true_200_100_2_trendup
  - waddahattarexplosion deadzone_150_10_true_9_30_true_9_30_2_true_200_100_2_trenddown
  - waddahattarexplosion deadzone_150_10_true_9_30_true_9_30_2_true_200_100_2_explosionline
  - waddahattarexplosion deadzone_150_10_true_9_30_true_9_30_2_true_200_100_2_deadzoneline
  - atr_14_atr
  - correlation_10_es sep25_correlation
  - barasatr_14_bar as atr %
  label_mapping:
    Strong Sell: 0
    Weak Sell: 1
    Hold: 2
    Weak Buy: 3
    Strong Buy: 4
