model_name: xgboost_20250905_133350
Type: XGBoostClassifier
artifact_paths:
  scaler: xgboost_20250905_133350_scaler.pkl
  model: xgboost_20250905_133350_model.json
Config:
  model_params:
    objective: multi:softmax
    eval_metric: mlogloss
    n_estimators: 150
    learning_rate: 0.1
    max_depth: 4
    use_label_encoder: false
    num_class: 5
  features:
  - open
  - high
  - low
  - close
  - volume
  - supertrendcciv2_cci
  - supertrendcciv2_ccima
  - supertrendcciv2_supertrend
  - supertrendcciv2_trenddirection
  - pricedistances_dist_ema_9
  - pricedistances_dist_ema_21
  - pricedistances_dist_t3_48
  - pricedistances_dist_copen
  - pricedistances_dist_chigh
  - pricedistances_dist_clow
  - pricedistances_dist_popen
  - pricedistances_dist_phigh
  - pricedistances_dist_plow
  - pricedistances_dist_pclose
  - pricedistances_dist_vwap
  - waddahattarexplosion deadzone_trendup
  - waddahattarexplosion deadzone_trenddown
  - waddahattarexplosion deadzone_explosionline
  - waddahattarexplosion deadzone_deadzoneline
  - atr_atr
  - correlation_correlation
  - barasatr_bar as atr %
  - opexatrbands_upperlimit
  - opexatrbands_lowerlimit
  - opexatrbands_daystoopex
  - timeplots_tradedayofyear
  - timeplots_dayofweekplot
  - timeplots_hourofday
  - timeplots_qrt15min
  label_mapping:
    Strong Sell: 0
    Weak Sell: 1
    Hold: 2
    Weak Buy: 3
    Strong Buy: 4
