model_name: 300Tick_NQ_SuperCCI
Type: Neural Network (Regression)
artifact_paths:
  scaler: 300Tick_NQ_SuperCCI_scaler.pkl
  model: 300Tick_NQ_SuperCCI_model.pt
Config:
  architecture:
  - type: Linear
    in_features: 34
    out_features: 64
  - type: ReLU
  - type: Dropout
    p: 0.3
  - type: Linear
    in_features: 64
    out_features: 32
  - type: ReLU
  - type: Linear
    in_features: 32
    out_features: 1
  train_params:
    optimizer: Adam
    loss: MSELoss
    learning_rate: 0.001
    epochs: 100
  features:
  - open
  - high
  - low
  - close
  - volume
  - supertrendcciv2_cci
  - supertrendcciv2_ccima
  - supertrendcciv2_supertrend
  - supertrendcciv2_trenddirection
  - pricedistances_dist_ema_9
  - pricedistances_dist_ema_21
  - pricedistances_dist_t3_48
  - pricedistances_dist_copen
  - pricedistances_dist_chigh
  - pricedistances_dist_clow
  - pricedistances_dist_popen
  - pricedistances_dist_phigh
  - pricedistances_dist_plow
  - pricedistances_dist_pclose
  - pricedistances_dist_vwap
  - waddahattarexplosion deadzone_trendup
  - waddahattarexplosion deadzone_trenddown
  - waddahattarexplosion deadzone_explosionline
  - waddahattarexplosion deadzone_deadzoneline
  - atr_atr
  - correlation_correlation
  - barasatr_bar as atr %
  - opexatrbands_upperlimit
  - opexatrbands_lowerlimit
  - opexatrbands_daystoopex
  - timeplots_tradedayofyear
  - timeplots_dayofweekplot
  - timeplots_hourofday
  - timeplots_qrt15min
